{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:16:27 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:37:07 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:46:59 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:47:42 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:47:46 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:47:53 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:48:03 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:48:10 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:48:16 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 12:59:52 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:00:39 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:02:01 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:05:06 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:05:28 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:05:41 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:07:15 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:15:09 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:16:56 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:17:26 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:17:37 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:22:33 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:23:03 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:24:58 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 02:00:20 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:08:08 PM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionError',
  parent: error: the database system is starting up
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'FATAL',
    code: '57P03',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postmaster.c',
    line: '2388',
    routine: 'ProcessStartupPacket'
  },
  original: error: the database system is starting up
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'FATAL',
    code: '57P03',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postmaster.c',
    line: '2388',
    routine: 'ProcessStartupPacket'
  },
  level: 'fatal',
  timestamp: '2023-04-09 01:08:52 PM',
  message: 'the database system is starting up',
  stack: 'SequelizeConnectionError: the database system is starting up\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:143:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:338:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:116:12\n' +
    '    at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:40:17)\n' +
    '    at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:324:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:297:9)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-10 09:32:54 AM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionError',
  parent: error: the database system is starting up
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'FATAL',
    code: '57P03',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postmaster.c',
    line: '2388',
    routine: 'ProcessStartupPacket'
  },
  original: error: the database system is starting up
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'FATAL',
    code: '57P03',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postmaster.c',
    line: '2388',
    routine: 'ProcessStartupPacket'
  },
  level: 'fatal',
  timestamp: '2023-04-10 09:36:35 AM',
  message: 'the database system is starting up',
  stack: 'SequelizeConnectionError: the database system is starting up\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:143:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:338:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:116:12\n' +
    '    at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:40:17)\n' +
    '    at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:324:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:297:9)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-23 11:45:21 AM',
  message: 'connect ECONNREFUSED 127.0.0.1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  identifier: '95da82dfdd32',
  level: 'fatal',
  timestamp: '2023-04-24 11:34:42 PM',
  message: 'User is not defined',
  stack: 'ReferenceError: User is not defined\n' +
    '    at getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:38:15)\n' +
    '    at loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:9)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at httpResponseValidation (/Users/enigma/Desktop/SADA/api/src/helpers/httpResponses.js:21:12)\n' +
    '    at loginValidateFormat (/Users/enigma/Desktop/SADA/api/src/validator/format/authFormatValidation.js:8:10)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at middleware (/Users/enigma/Desktop/SADA/api/node_modules/express-validator/src/middlewares/check.js:16:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  identifier: '5293de1b2698',
  level: 'fatal',
  timestamp: '2023-04-24 11:35:07 PM',
  message: 'AccountVerification is not defined',
  stack: 'ReferenceError: AccountVerification is not defined\n' +
    '    at getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:48:12)\n' +
    '    at loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:9)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at httpResponseValidation (/Users/enigma/Desktop/SADA/api/src/helpers/httpResponses.js:21:12)\n' +
    '    at loginValidateFormat (/Users/enigma/Desktop/SADA/api/src/validator/format/authFormatValidation.js:8:10)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at middleware (/Users/enigma/Desktop/SADA/api/node_modules/express-validator/src/middlewares/check.js:16:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  identifier: 'f2847b340619',
  level: 'fatal',
  timestamp: '2023-04-24 11:46:35 PM',
  message: 'AccountVerification is not defined',
  stack: 'ReferenceError: AccountVerification is not defined\n' +
    '    at getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:48:12)\n' +
    '    at loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:9)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at httpResponseValidation (/Users/enigma/Desktop/SADA/api/src/helpers/httpResponses.js:21:12)\n' +
    '    at loginValidateFormat (/Users/enigma/Desktop/SADA/api/src/validator/format/authFormatValidation.js:8:10)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at middleware (/Users/enigma/Desktop/SADA/api/node_modules/express-validator/src/middlewares/check.js:16:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  identifier: 'ee3664b35c73',
  level: 'fatal',
  timestamp: '2023-04-24 11:47:59 PM',
  message: 'AccountVerification is not defined',
  stack: 'ReferenceError: AccountVerification is not defined\n' +
    '    at getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:48:12)\n' +
    '    at loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:9)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at httpResponseValidation (/Users/enigma/Desktop/SADA/api/src/helpers/httpResponses.js:21:12)\n' +
    '    at loginValidateFormat (/Users/enigma/Desktop/SADA/api/src/validator/format/authFormatValidation.js:8:10)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at middleware (/Users/enigma/Desktop/SADA/api/node_modules/express-validator/src/middlewares/check.js:16:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  identifier: 'a0720b0d3b14',
  level: 'fatal',
  timestamp: '2023-04-24 11:48:59 PM',
  message: 'UserRole is not defined',
  stack: 'ReferenceError: UserRole is not defined\n' +
    '    at getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:48:11)\n' +
    '    at loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:9)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at httpResponseValidation (/Users/enigma/Desktop/SADA/api/src/helpers/httpResponses.js:21:12)\n' +
    '    at loginValidateFormat (/Users/enigma/Desktop/SADA/api/src/validator/format/authFormatValidation.js:8:10)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at middleware (/Users/enigma/Desktop/SADA/api/node_modules/express-validator/src/middlewares/check.js:16:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: '963f7ea69d5f',
  level: 'fatal',
  timestamp: '2023-04-24 11:49:10 PM',
  message: 'UserRole is not associated to User!',
  stack: 'SequelizeEagerLoadingError: UserRole is not associated to User!\n' +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:565:13)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: '494990eafc74',
  level: 'fatal',
  timestamp: '2023-04-25 12:02:44 AM',
  message: 'UserRole is not associated to User!',
  stack: 'SequelizeEagerLoadingError: UserRole is not associated to User!\n' +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:565:13)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: 'f56353387b13',
  level: 'fatal',
  timestamp: '2023-04-25 12:11:45 AM',
  message: 'UserRole is not associated to User!',
  stack: 'SequelizeEagerLoadingError: UserRole is not associated to User!\n' +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:565:13)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: column User.username does not exist
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '21',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3651',
    routine: 'errorMissingColumn',
    sql: `SELECT "User"."id", "User"."username", "Account"."password", "Account"."email", "Account"."account_state" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  original: error: column User.username does not exist
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '21',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3651',
    routine: 'errorMissingColumn',
    sql: `SELECT "User"."id", "User"."username", "Account"."password", "Account"."email", "Account"."account_state" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."username", "Account"."password", "Account"."email", "Account"."account_state" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
  parameters: {},
  identifier: 'cbacf305e190',
  level: 'fatal',
  timestamp: '2023-04-25 12:14:34 AM',
  message: 'column User.username does not exist',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  identifier: '9a94d4018d7d',
  level: 'fatal',
  timestamp: '2023-04-25 12:15:18 AM',
  message: 'Role is not defined',
  stack: 'ReferenceError: Role is not defined\n' +
    '    at getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:49:11)\n' +
    '    at loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:9)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at httpResponseValidation (/Users/enigma/Desktop/SADA/api/src/helpers/httpResponses.js:21:12)\n' +
    '    at loginValidateFormat (/Users/enigma/Desktop/SADA/api/src/validator/format/authFormatValidation.js:8:10)\n' +
    '    at Layer.handle [as handle_request] (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/enigma/Desktop/SADA/api/node_modules/express/lib/router/route.js:144:13)\n' +
    '    at middleware (/Users/enigma/Desktop/SADA/api/node_modules/express-validator/src/middlewares/check.js:16:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  original: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
  parameters: {},
  identifier: 'a8966cd1c1c0',
  level: 'fatal',
  timestamp: '2023-04-25 12:17:31 AM',
  message: 'invalid reference to FROM-clause entry for table "Role"',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:41:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: '73f103906b74',
  level: 'fatal',
  timestamp: '2023-04-25 12:18:13 AM',
  message: "Role is associated to User using an alias. You've included an alias (Role), but it does not match the alias(es) defined in your association (Roles).",
  stack: "SequelizeEagerLoadingError: Role is associated to User using an alias. You've included an alias (Role), but it does not match the alias(es) defined in your association (Roles).\n" +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:574:15)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:41:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  original: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
  parameters: {},
  identifier: '1e9c2e1d039a',
  level: 'fatal',
  timestamp: '2023-04-25 12:18:31 AM',
  message: 'invalid reference to FROM-clause entry for table "Role"',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:41:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: '7e4752c593d6',
  level: 'fatal',
  timestamp: '2023-04-25 12:40:52 AM',
  message: "Role is associated to User using an alias. You've included an alias (Role), but it does not match the alias(es) defined in your association (Roles).",
  stack: "SequelizeEagerLoadingError: Role is associated to User using an alias. You've included an alias (Role), but it does not match the alias(es) defined in your association (Roles).\n" +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:574:15)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:41:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  original: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'test@hotmail.com';`,
  parameters: {},
  identifier: '656a6b1c3f68',
  level: 'fatal',
  timestamp: '2023-04-25 12:41:42 AM',
  message: 'invalid reference to FROM-clause entry for table "Role"',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:41:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-25 08:41:39 PM',
  message: 'connect ECONNREFUSED 127.0.0.1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: '7f63ce9ed726',
  level: 'fatal',
  timestamp: '2023-04-25 08:52:34 PM',
  message: 'Role is not associated to User!',
  stack: 'SequelizeEagerLoadingError: Role is not associated to User!\n' +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:565:13)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeEagerLoadingError',
  identifier: 'bff1ec6d9a5f',
  level: 'fatal',
  timestamp: '2023-04-25 08:54:07 PM',
  message: 'Role is not associated to User!',
  stack: 'SequelizeEagerLoadingError: Role is not associated to User!\n' +
    '    at User._getIncludedAssociation (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:565:13)\n' +
    '    at User._validateIncludedElement (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:502:53)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:421:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at User._validateIncludedElements (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:417:39)\n' +
    '    at User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1124:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: column User.id_user does not exist
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '253',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3651',
    routine: 'errorMissingColumn',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN "Role" AS "Role" ON "User"."id_user" = "Role"."id" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  original: error: column User.id_user does not exist
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 111,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '253',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3651',
    routine: 'errorMissingColumn',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN "Role" AS "Role" ON "User"."id_user" = "Role"."id" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN "Role" AS "Role" ON "User"."id_user" = "Role"."id" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
  parameters: {},
  identifier: '412197c0fa4f',
  level: 'fatal',
  timestamp: '2023-04-25 08:56:06 PM',
  message: 'column User.id_user does not exist',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: missing FROM-clause entry for table "Roles"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 117,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3603',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN "Role" AS "Role" ON "User"."id_user" = "Role"."id" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  original: error: missing FROM-clause entry for table "Roles"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 117,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3603',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN "Role" AS "Role" ON "User"."id_user" = "Role"."id" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN "Role" AS "Role" ON "User"."id_user" = "Role"."id" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
  parameters: {},
  identifier: 'a3890fe5aec5',
  level: 'fatal',
  timestamp: '2023-04-25 08:56:39 PM',
  message: 'missing FROM-clause entry for table "Roles"',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: missing FROM-clause entry for table "Roles"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 117,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3603',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  original: error: missing FROM-clause entry for table "Roles"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 117,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3603',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Roles"."name" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
  parameters: {},
  identifier: 'a05c3a83663b',
  level: 'fatal',
  timestamp: '2023-04-25 08:57:18 PM',
  message: 'missing FROM-clause entry for table "Roles"',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  name: 'SequelizeDatabaseError',
  parent: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Role"."id", "Roles"."id" AS "Roles.id", "Roles"."name" AS "Roles.name", "Roles"."creation_date" AS "Roles.creation_date", "Roles"."update_date" AS "Roles.update_date", "Roles"."id_business" AS "Roles.id_business", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  original: error: invalid reference to FROM-clause entry for table "Role"
      at Parser.parseErrorMessage (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/enigma/Desktop/SADA/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 186,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: 'Perhaps you meant to reference the table alias "Roles".',
    position: '104',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3592',
    routine: 'errorMissingRTE',
    sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Role"."id", "Roles"."id" AS "Roles.id", "Roles"."name" AS "Roles.name", "Roles"."creation_date" AS "Roles.creation_date", "Roles"."update_date" AS "Roles.update_date", "Roles"."id_business" AS "Roles.id_business", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
    parameters: undefined
  },
  sql: `SELECT "User"."id", "User"."name", "Account"."password", "Account"."email", "Account"."account_state", "Role"."name", "Role"."id", "Roles"."id" AS "Roles.id", "Roles"."name" AS "Roles.name", "Roles"."creation_date" AS "Roles.creation_date", "Roles"."update_date" AS "Roles.update_date", "Roles"."id_business" AS "Roles.id_business", "Roles->UserRole"."id_user" AS "Roles.UserRole.id_user", "Roles->UserRole"."id_role" AS "Roles.UserRole.id_role" FROM "User" AS "User" LEFT OUTER JOIN "Account" AS "Account" ON "User"."id" = "Account"."id_user" LEFT OUTER JOIN ( "UserRole" AS "Roles->UserRole" INNER JOIN "Role" AS "Roles" ON "Roles"."id" = "Roles->UserRole"."id_role") ON "User"."id" = "Roles->UserRole"."id_user" WHERE "Account"."email" = 'robertoperez@hotmail.com';`,
  parameters: {},
  identifier: 'ae6cf9319605',
  level: 'fatal',
  timestamp: '2023-04-25 09:35:57 PM',
  message: 'invalid reference to FROM-clause entry for table "Role"',
  stack: 'Error\n' +
    '    at Query.run (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n' +
    '    at /Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/sequelize.js:315:28\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PostgresQueryInterface.select (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\n' +
    '    at async User.findAll (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/model.js:1140:21)\n' +
    '    at async getAccountLoginData (/Users/enigma/Desktop/SADA/api/src/services/dataaccess/account.js:40:15)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:8:3)'
}
{
  identifier: '833d7a7abab7',
  level: 'fatal',
  timestamp: '2023-04-26 04:18:08 PM',
  message: 'userData is not defined',
  stack: 'ReferenceError: userData is not defined\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:11:4\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:9:3)'
}
{
  identifier: '6745ac43a42c',
  level: 'fatal',
  timestamp: '2023-04-26 04:18:42 PM',
  message: 'doesPasswordMatch is not defined',
  stack: 'ReferenceError: doesPasswordMatch is not defined\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:14:4\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:9:3)'
}
{
  identifier: '18c6380799e0',
  level: 'fatal',
  timestamp: '2023-04-26 04:22:36 PM',
  message: 'encondePassword is not defined',
  stack: 'ReferenceError: encondePassword is not defined\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:15:4\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:10:3)'
}
{
  identifier: '145c6e76f45e',
  level: 'fatal',
  timestamp: '2023-04-26 04:23:46 PM',
  message: 'passwordCrypted is not defined',
  stack: 'ReferenceError: passwordCrypted is not defined\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:15:36\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:10:3)'
}
{
  identifier: 'b096693b93e6',
  level: 'fatal',
  timestamp: '2023-04-26 04:24:00 PM',
  message: 'createHash is not defined',
  stack: 'ReferenceError: createHash is not defined\n' +
    '    at encondeSHA256 (/Users/enigma/Desktop/SADA/api/src/helpers/crypt.js:2:18)\n' +
    '    at doesPasswordMatch (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:31:5)\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:15:8\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:10:3)'
}
{
  identifier: 'e9d724d4df1e',
  level: 'fatal',
  timestamp: '2023-04-26 04:27:48 PM',
  message: 'httpResponseForbidden is not defined',
  stack: 'ReferenceError: httpResponseForbidden is not defined\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:18:5\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:10:3)'
}
{
  identifier: '560162937ace',
  level: 'fatal',
  timestamp: '2023-04-26 05:40:15 PM',
  message: 'httpMessageCodes is not defined',
  stack: 'ReferenceError: httpMessageCodes is not defined\n' +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:18:44\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:10:3)'
}
{
  identifier: 'a93dd4b1875a',
  level: 'fatal',
  timestamp: '2023-04-26 07:33:32 PM',
  message: "Cannot read properties of null (reading 'account_status')",
  stack: "TypeError: Cannot read properties of null (reading 'account_status')\n" +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:13:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:11:3)'
}
{
  identifier: 'e3953120209a',
  level: 'fatal',
  timestamp: '2023-04-26 07:33:47 PM',
  message: "Cannot read properties of null (reading 'account_status')",
  stack: "TypeError: Cannot read properties of null (reading 'account_status')\n" +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:13:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:11:3)'
}
{
  identifier: '5bc1abd670d1',
  level: 'fatal',
  timestamp: '2023-04-26 07:35:20 PM',
  message: "Cannot read properties of null (reading 'account_status')",
  stack: "TypeError: Cannot read properties of null (reading 'account_status')\n" +
    '    at /Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:13:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async loginDataValidation (/Users/enigma/Desktop/SADA/api/src/controllers/validations/authDataValidation.js:11:3)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-27 02:48:19 PM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-28 10:17:25 PM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
{
  name: 'SequelizeConnectionRefusedError',
  parent: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED ::1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5432
  },
  level: 'fatal',
  timestamp: '2023-04-29 02:01:22 PM',
  message: 'connect ECONNREFUSED ::1:5432',
  stack: 'SequelizeConnectionRefusedError: connect ECONNREFUSED ::1:5432\n' +
    '    at Client._connectionCallback (/Users/enigma/Desktop/SADA/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n' +
    '    at Client._handleErrorWhileConnecting (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:318:19)\n' +
    '    at Client._handleErrorEvent (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/client.js:328:19)\n' +
    '    at Connection.emit (node:events:513:28)\n' +
    '    at Socket.reportStreamError (/Users/enigma/Desktop/SADA/api/node_modules/pg/lib/connection.js:57:12)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)'
}
